#! /bin/sh

# -- Autostart System --
killall sxhkd
killall polybar
killall picom

sxhkd &
$HOME/.config/polybar/launch.sh
nitrogen --restore &
picom -f &

# -- Autostart Applications --
pgrep -x chromium > /dev/null || chromium &
pgrep -x discord > /dev/null || discord &
pgrep -x geary > /dev/null || geary &
pgrep -x jetbrains-toolbox > /dev/null || jetbrains-toolbox &


bspc monitor DP-2 -d I II III IV V VI
bspc monitor DP-4 -d VII VIII IX X

bspc config border_width   	 2
bspc config window_gap		 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop='^10'
bspc rule -a discord desktop='^9'
bspc rule -a Geary desktop='^6'
bspc rule -a Clion dekstop='^3'
bspc rule -a IntelliJ desktop='^4'
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a factorio desktop='^5' state=fullscreen
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
